CREATE TABLE Talabalar2 (
TalabaID INT PRIMARY KEY IDENTITY(1,1), 
Ism NVARCHAR(50) NOT NULL,
Familiya NVARCHAR(50) NOT NULL, 
TugilganYil INT DEFAULT 2000, 
FakultetID INT, CONSTRAINT FK_Fakultet FOREIGN KEY (FakultetID) REFERENCES Fakultetlar(FakultetID));