FOREIGN KEY -- BOSHQA JADVALDAGI USTUNGA BOG'LANADI. MA'LUMOTLAR INTEGRATSIYASINI TANMINLAYDI 
PRIMARY KEY -- JADVALDAGI YAGONA VA NOYOB USTUN.ODATDA ID UCHUN ISHLATILADI.
DEFAULT -- FOYDALANUVCHI QIYMAT BERMASA, AVTAMATIK KIRITILADIGAN STANDART QIYMAT
NULL -- QOYMAT YO'QLIGINI BILDIRADI
NOT NULL -- QIYMAT BO'LISHI SHARTLIGINI BILDIRADI
IDENTITY -- AVTOMOTIK TARZDA SONNI OSHIRIB BORADI. MASALAN: 1,2,3...  